### ISSUE TITLE
check permissions on .conf before opening

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-bouncer#16]
https://github.com/reap3r/firewall/blob/82cdd5a3455fa5d72630ecdabefba705507d84b4/appliance/src/rest_interface.py#L23

before opening up the conf file, this program should check the permissions and error-out if they are inadvisable. Think of ssh which won't exec if you have .ssh files that are world-readable. This config has secrets in it and the persmissions on the file should be such that only this user account can read the file.

see also issue #15 ; in that case it is important to ensure that it couldn't have been modified by a lesser privilege (e.g. that it has `w` only on the root account -- but other schemes would probably be fine too)

**Comment by reap3r** [comment]
There are no longer secrets in the .conf file. Do you think this still needs to be corrected?

**Comment by BenGardiner** [comment]
I think they are still read from the conf. 
https://github.com/reap3r/nmfta-bouncer/blob/master/appliance/src/rest_interface.py#L32

cc @krishnaswin

**Comment by krishnaswin** [comment]
updated code to check configuration file permission before loading
