### ISSUE TITLE
static analysis before we go

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-bouncer#19]
Let's also run the static analysis checks recommended here before we ship.

https://before-you-ship.18f.gov/security/static-analysis/#recommendations-by-language

I can do this step; but it's best to repeat the dependency checks in the production environment to ensure available versions are scanned.

**Comment by BenGardiner** [comment]
I doubt I'll have time to do this. dropping myself from assignees

**Comment by BenGardiner** [comment]
[bengardiner:~/homehome/src/nmfta-bouncer] master 2 ± ~/.local/bin/bandit -r appliance/
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.5.3
Run started:2019-04-29 18:51:49.838737

Test results:
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: appliance/src/rest_interface.py:32
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
31      APP.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
32      APP.config['SECRET_KEY'] = ''.join([random.choice(string.ascii_letters+string.digits) for n in range(32)])
33      APP.config['PROPAGATE_EXCEPTIONS'] = True

--------------------------------------------------
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: appliance/src/rest_interface.py:36
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
35      DB.create_all(app=APP)
36      APP.config['JWT_SECRET_KEY'] = ''.join([random.choice(string.ascii_letters+string.digits) for n in range(32)])
37      JWT = JWTManager(APP)

--------------------------------------------------
>> Issue: [B608:hardcoded_sql_expressions] Possible SQL injection vector through string-based query construction.
   Severity: Medium   Confidence: Medium
   Location: appliance/src/rules_scheduler.py:22
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b608_hardcoded_sql_expressions.html
21              if row[2]:
22                  conn.execute("DELETE FROM iptable WHERE id={}".format(row[0]))
23                  conn.commit()

--------------------------------------------------
>> Issue: [B608:hardcoded_sql_expressions] Possible SQL injection vector through string-based query construction.
   Severity: Medium   Confidence: Medium
   Location: appliance/src/rules_scheduler.py:31
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b608_hardcoded_sql_expressions.html
30              if row[2]:
31                  conn.execute("DELETE FROM iptable WHERE id={}".format(row[0]))
32                  conn.commit()

--------------------------------------------------
>> Issue: [B110:try_except_pass] Try, Except, Pass detected.
   Severity: Low   Confidence: High
   Location: appliance/src/ufw_interface.py:104
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html
103                 rule_port = int(rule.dport)
104             except:
105                 pass

--------------------------------------------------

Code scanned:
        Total lines of code: 788
        Total lines skipped (#nosec): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0.0
                Low: 3.0
                Medium: 2.0
                High: 0.0
        Total issues (by confidence):
                Undefined: 0.0
                Low: 0.0
                Medium: 2.0
                High: 3.0
Files skipped (0):
[bengardiner:~/homehome/src/nmfta-bouncer] master 1

**Comment by krishnaswin** [comment]
updated source to fix issues identified by bandit
Also added requirements file to identify package dependencies and fix security warnings
