### ISSUE TITLE
return code non-200 for errors

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-bouncer#21]
the way APImatic models APIs requires errors are returned with an HTTP status code other than 200.

the change I'm proposing is to return status code 400 along with all the errors already returned by Bouncer.

(I can make the change if it's OK)

**Comment by BenGardiner** [comment]
@krishnaswin -- if this is OK considering your existing client code.

**Comment by ujonson** [comment]
fine by me.

**Comment by krishnaswin** [comment]
I think this is fine, we only have one client to update at this time
