### ISSUE TITLE
migrate away from `Flask.run()`

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-bouncer#24]
`rest_interface.py` launches the webserver using `Flask.run()` against the reccomendations of flask for production code

> Do not use run() in a production setting. It is not intended to meet security and performance requirements for a production server. Instead, see Deployment Options for WSGI server recommendations.
from http://flask.pocoo.org/docs/1.0/api/#flask.Flask.run

**Comment by krishnaswin** [comment]
Add wsgi and configuration for running site in apache.
