### ISSUE TITLE
Upload Bouncer Installation v1 documentation

### ISSUE THREAD

**Issue by HVCSFriend** [nmfta-repo/nmfta-bouncer#36]
[Bouncer Installation Document v1.pdf](https://github.com/nmfta-repo/nmfta-bouncer/files/3188164/Bouncer.Installation.Document.v1.pdf)

Not able to create a pull request or permissioned to upload files.

**Comment by BenGardiner** [comment]
I'm pretty sure this was committed in https://github.com/nmfta-repo/nmfta-bouncer/commit/d997f142ac989ab97df54106feb7e77752079c25
